services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
#      - 'PGDATA=/var/lib/postgresql/data'
#    volumes:
#      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
#  pgadmin4:
#    image: 'elestio/pgadmin:latest'
#    #restart: always
#    environment:
#      - 'PGADMIN_DEFAULT_EMAIL=admin@email.com'
#      - 'PGADMIN_DEFAULT_PASSWORD=root'
#
#    ports:
#      - "8082:8080"
#    volumes:
#      - ./servers.json:/pgadmin4/servers.json
